### ISSUE TITLE
can't start on Android 12

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [CYB3R-G0D/File-Manager#1]
I tried to start File Manager, but it didn't work.

I could only install it.

Phone:  Samsung S21 5G 
OS: Android 12

**Comment by qokrb2t** [comment]
Same here. App does not start or pops up the 'app keeps stopping' message on lineageos 19.1

**Comment by HonestAbe7** [comment]
Yes, app crashed for me too on Android 10 on a cheap LG phone.

**Comment by benoit-tlr** [comment]
Here is the error log I got, hope it can help
I'm on A12.1
`java.lang.NullPointerException: Attempt to get length of null array
	at com.cyb3rg0d.filemanager.ui.HomeUI.findFiles(HomeUI.java:173)
	at com.cyb3rg0d.filemanager.ui.HomeUI.findFiles(HomeUI.java:175)
	at com.cyb3rg0d.filemanager.ui.HomeUI.findFiles(HomeUI.java:175)
	at com.cyb3rg0d.filemanager.ui.HomeUI.filesDisplay(HomeUI.java:191)
	at com.cyb3rg0d.filemanager.ui.HomeUI.access$000(HomeUI.java:54)
	at com.cyb3rg0d.filemanager.ui.HomeUI$7.onPermissionsChecked(HomeUI.java:158)
	at com.karumi.dexter.DexterInstance$1.run(Unknown Source:43)
	at com.karumi.dexter.MainThread.execute(Unknown Source:6)
	at com.karumi.dexter.DexterInstance.checkMultiplePermissions(Unknown Source:71)
	at com.karumi.dexter.DexterInstance.checkPermissions(Unknown Source:0)
	at com.karumi.dexter.Dexter.check(Unknown Source:10)
	at com.cyb3rg0d.filemanager.ui.HomeUI.runtimePermission(HomeUI.java:165)
	at com.cyb3rg0d.filemanager.ui.HomeUI.onCreateView(HomeUI.java:147)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1473)
	at android.app.Activity.performStart(Activity.java:8082)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3732)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7877)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)`

**Comment by CYB3R-G0D** [comment]
Thank you for reporting this issue. 
Android API level 29 and above made some changes in storage access.
Also this app crashes due to fileList returning null as there is an issue accessing storage.

I have fixed this issue now. But it still has some issues like `/storage/emulate/0/Android` file can't be opened, file operation / folder creation won't work in the main directory `/storage/emulate/0/` so I'm working on this and will release a fixed version soon that supports API level 29+.

Check if this debug apk doesn't crash after opening (It only stops crashes and is for test purpose the above issues are applicable).
[app-debug.zip](https://github.com/CYB3R-G0D/File-Manager/files/8931164/app-debug.zip)

**Comment by benoit-tlr** [comment]
It starts fine on A12.1

**Comment by CYB3R-G0D** [comment]
@benoit-tlr Does it display recent files in home directory?

**Comment by benoit-tlr** [comment]
No it doesn't for me

**Comment by CYB3R-G0D** [comment]
Ok there must be array sorting problem there. Does the file operations (rename, delete ,create) working in the main directory for you?

**Comment by benoit-tlr** [comment]
I tested in `/storage/emulated/0` and I can't create or delete folders, nor rename files

**Comment by CYB3R-G0D** [comment]
Android 12 doesn't allow the file operations in  the root directory `/storage/emulated/0` but it works inside a specific folder like Downloads, Documents. Also I guess it needs special permission to access the `Android` folder in root directory (it crashes if tried to open). I will work on it.

**Comment by benoit-tlr** [comment]
Indeed I can create & delete folders inside another folders. However I couldn't rename a file, when I click OK there's a toast that says "rename" but nothing happens.
